<template>
  <el-form :model="form" :rules="rules" ref="elForm" size="mini" label-width="100px" class="elform">
    <el-row><el-col><div class="el-form-item__label el-form-item__label_text">该表为自评表，根据下表中5个方面进行评估，将各方面判断评分汇总后，0-3分者为可自理； 4-8分者为轻度依赖；9-18分者为中度依赖； ≥19分者为不能自理。</div></el-col></el-row>
    <el-row><el-col><el-form-item label="评估时间" prop="assess_time"><div class="block"/><el-date-picker class="ud-inputdate" v-model="form.assess_time" type="date" placeholder="选择日期" value-format="yyyy-MM-dd"/></el-form-item></el-col></el-row>
    <el-row><el-col :span="24"><div class="el-form-item__label_group">（1）进餐：使用餐具将饭菜送入口、咀嚼、吞咽等活动</div></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="" prop="assess_food"><el-radio v-model="form.assess_food" :label="1" border="border">独立完成</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="" prop="assess_food"><el-radio v-model="form.assess_food" :label="2" border="border">——</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="" prop="assess_food"><el-radio v-model="form.assess_food" :label="3" border="border">需要协助，如切碎、搅拌食物等</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="" prop="assess_food"><el-radio v-model="form.assess_food" :label="4" border="border">完全需要帮助</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :span="24"><div class="el-form-item__label_group">（2）梳洗：梳头、洗脸、刷牙、剃须洗澡等活动</div></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="" prop="assess_wash"><el-radio v-model="form.assess_wash" :label="1" border="border">独立完成</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="" prop="assess_wash"><el-radio v-model="form.assess_wash" :label="2" border="border">能独立地洗头、梳头、洗脸、刷牙、剃须等；洗澡需要协助</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="" prop="assess_wash"><el-radio v-model="form.assess_wash" :label="3" border="border">在协助下和适当的时间内，能完成部分梳洗活动</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="" prop="assess_wash"><el-radio v-model="form.assess_wash" :label="4" border="border">完全需要帮助</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :span="24"><div class="el-form-item__label_group">（3）穿衣：穿衣裤、袜子、鞋子等活动</div></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="穿衣" prop="assess_dress"><el-radio v-model="form.assess_dress" :label="1" border="border">独立完成</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="穿衣" prop="assess_dress"><el-radio v-model="form.assess_dress" :label="2" border="border">——</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="穿衣" prop="assess_dress"><el-radio v-model="form.assess_dress" :label="3" border="border">需要协助，在适当的时间内完成部分穿衣</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="穿衣" prop="assess_dress"><el-radio v-model="form.assess_dress" :label="4" border="border">完全需要帮助</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :span="24"><div class="el-form-item__label_group">（4）如厕：小便、大便等活动及自控</div></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="如厕" prop="assess_wc"><el-radio v-model="form.assess_wc" :label="1" border="border">不需协助，可自控</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="如厕" prop="assess_wc"><el-radio v-model="form.assess_wc" :label="2" border="border">偶尔失禁，但基本上能如厕或使用便具</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="如厕" prop="assess_wc"><el-radio v-model="form.assess_wc" :label="3" border="border">经常失禁，在很多提示和协助下尚能如厕或使用便具</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="如厕" prop="assess_wc"><el-radio v-model="form.assess_wc" :label="4" border="border">完全失禁，完全需要帮助</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :span="24"><div class="el-form-item__label_group">（5）活动：站立、室内行走、上下楼梯、户外活动</div></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="活动" prop="assess_sport"><el-radio v-model="form.assess_sport" :label="1" border="border">独立完成所有活动</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="活动" prop="assess_sport"><el-radio v-model="form.assess_sport" :label="2" border="border">借助较小的外力或辅助装置能完成站立、行走、上下楼梯等</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="活动" prop="assess_sport"><el-radio v-model="form.assess_sport" :label="3" border="border">借助较大的外力才能完成站立、行走，不能上下楼梯</el-radio></el-form-item></el-col><el-col :xs="24" :sm="12" :md="12" :lg="12"><el-form-item label="活动" prop="assess_sport"><el-radio v-model="form.assess_sport" :label="4" border="border">卧床不起，活动完全需要帮助</el-radio></el-form-item></el-col></el-row>
    <el-row><el-col :span="24"><div class="el-form-item__label_group">结果</div></el-col></el-row>
    <el-row><el-col :xs="24" :sm="12" :md="6" :lg="6"><el-form-item label="评估总分" prop="assess_score"><el-input v-model="form.assess_score"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="6" :lg="6"><el-form-item label="评估人姓名" prop="assess_operator_name"><ud-input-select v-model="form.assess_operator_name" dataUrl="/PHOrganizationDict/getDict?dictName=team_doctor" columnName="assess_operator_name" :setValue="setValueByDict" :readonly="readonlyFlag.readonly_assess_operator_name"/></el-form-item></el-col><el-col :xs="24" :sm="12" :md="6" :lg="6"><el-form-item label="评估结果" prop="assess_result"><ud-select v-model="form.assess_result" dataUrl="/PHBaseDict/getDict?dictName=assess_result"/></el-form-item></el-col></el-row>
  </el-form>
</template>
<script src="./ElderlyOneselfAssessForm.js"></script>
<style scoped src="../../../assets/css/base-form.css"></style>
